/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import desain.GradientPanel;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import javax.swing.UIManager;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import kasir_warmad.Koneksi;
import kasir_warmad.Laporan;
import kasir_warmad.Session;

/**
 *
 * @author ThinkPad
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String role) {
        initComponents();
        
        
        Logo.setIcon(new FlatSVGIcon("image/Log.svg", 100, 50));
    
   if (role.equalsIgnoreCase("kasir")) {
        LaporanD.setVisible(false);
    } else if (role.equalsIgnoreCase("admin")) {
        LaporanD.setVisible(true);
    } else {
        LaporanD.setVisible(false);
    }}

        
    private void loadDataTransaksiTerbaru() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Terjual");
        model.addColumn("Total Harga");
        model.addColumn("Metode Pembayaran");
        model.addColumn("Tanggal");

        try {
            String sql = "SELECT bj.barcode_barang, bj.nama_barang, dt.jumlah, tk.total_harga, "
                    + "tk.metode_pembayaran, tk.tanggal "
                    + "FROM transaksi_kasir tk "
                    + "JOIN detail_transaksi_pelanggan dt ON tk.id_transaksi_kasir = dt.id_transaksi_kasir "
                    + "JOIN barang_jual bj ON dt.id_barang_jual = bj.id_barang_jual "
                    + "ORDER BY tk.tanggal DESC "
                    + "LIMIT 20";  // atau LIMIT sesuai kebutuhan

            Connection conn = Koneksi.getKoneksi();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("barcode_barang"),
                    res.getString("nama_barang"),
                    res.getInt("jumlah"),
                    res.getDouble("total_harga"),
                    res.getString("metode_pembayaran"),
                    res.getTimestamp("tanggal")
                });
            }

            TabeltransaksibaruD.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Transaksi Terbaru: " + e.getMessage());
        }}
        private void loadDataBarangTerlaris() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Stok");
        model.addColumn("Total Terjual");

        try {
            String sql = "SELECT bj.barcode_barang, bj.nama_barang, bj.kategori_barang, sg.jumlah_stok, "
                    + "SUM(dt.jumlah) AS total_terjual "
                    + "FROM detail_transaksi_pelanggan dt "
                    + "JOIN barang_jual bj ON dt.id_barang_jual = bj.id_barang_jual "
                    + "LEFT JOIN stok_gudang sg ON bj.id_barang_jual = sg.id_barang_jual "
                    + "GROUP BY bj.barcode_barang, bj.nama_barang, bj.kategori_barang, sg.jumlah_stok "
                    + "ORDER BY total_terjual DESC "
                    + "LIMIT 10";

            Connection conn = Koneksi.getKoneksi();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("barcode_barang"),
                    res.getString("nama_barang"),
                    res.getString("kategori_barang"),
                    res.getInt("jumlah_stok"),
                    res.getInt("total_terjual")
                });
            }

            TabelbarangterlarisD.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Barang Terlaris: " + e.getMessage());
        }
  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new GradientPanel();
        TransaksiD = new javax.swing.JButton();
        LaporanD = new javax.swing.JButton();
        KelolabarangD = new javax.swing.JButton();
        StokbarangD = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jPanel3 = new GradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabeltransaksibaruD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelbarangterlarisD = new javax.swing.JTable();
        LogoutD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1244, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1245, 768));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TransaksiD.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        TransaksiD.setText("Transaksi");
        TransaksiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiDActionPerformed(evt);
            }
        });

        LaporanD.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        LaporanD.setText("Laporan");
        LaporanD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanDActionPerformed(evt);
            }
        });

        KelolabarangD.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        KelolabarangD.setText("Kelola Barang");
        KelolabarangD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelolabarangDActionPerformed(evt);
            }
        });

        StokbarangD.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        StokbarangD.setText("Stok Barang");
        StokbarangD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokbarangDActionPerformed(evt);
            }
        });

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new FlatSVGIcon("image/Log.svg"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StokbarangD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KelolabarangD, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(LaporanD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransaksiD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TransaksiD)
                .addGap(18, 18, 18)
                .addComponent(LaporanD)
                .addGap(18, 18, 18)
                .addComponent(KelolabarangD)
                .addGap(18, 18, 18)
                .addComponent(StokbarangD)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TabeltransaksibaruD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabeltransaksibaruD);

        TabelbarangterlarisD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabelbarangterlarisD);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogoutD.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        LogoutD.setText("Log Out");
        LogoutD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoutD)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LogoutD)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutDActionPerformed
        login lg = new login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        dispose();
        javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGOUT");
    }//GEN-LAST:event_LogoutDActionPerformed

    private void StokbarangDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokbarangDActionPerformed
        Stok_barang sb = new Stok_barang();
        sb.setVisible(true);
        sb.pack();
        sb.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_StokbarangDActionPerformed

    private void KelolabarangDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolabarangDActionPerformed
        Kelola_barang kb = new Kelola_barang();
        kb.setVisible(true);
        kb.pack();
        kb.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_KelolabarangDActionPerformed

    private void LaporanDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanDActionPerformed
        Laporan la = new Laporan();
        la.setVisible(true);
        la.pack();
        la.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_LaporanDActionPerformed

    private void TransaksiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiDActionPerformed
        Transaksi t = new Transaksi();       // buat objek
        t.setLocationRelativeTo(null);       // posisikan di tengah
        t.setVisible(true);                  // tampilkan
    }//GEN-LAST:event_TransaksiDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadDataTransaksiTerbaru();  
        loadDataBarangTerlaris();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
            UIManager.put("Button.arc", 999);
            UIManager.put("defaultFont", new Font("Poppins", Font.BOLD, 14));

        } catch (Exception ex) {
            System.err.println("Gagal mengatur tema FlatLaf Arc Orange.");
            ex.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(Session.getCurrentUserRole()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KelolabarangD;
    private javax.swing.JButton LaporanD;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton LogoutD;
    private javax.swing.JButton StokbarangD;
    private javax.swing.JTable TabelbarangterlarisD;
    private javax.swing.JTable TabeltransaksibaruD;
    private javax.swing.JButton TransaksiD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
