/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.Font;
import javax.swing.UIManager;
import kasir_warmad.tampilan.tambah_barang;
import kasir_warmad.tampilan.tambah_stok;
import javax.swing.table.DefaultTableModel;
import kasir_warmad.tampilan.tambah_barang;
import kasir_warmad.tampilan.tambah_stok;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import kasir_warmad.Koneksi;
import desain.GradientPanel;

/**
 *
 * @author ThinkPad
 */
public class Kelola_barang extends javax.swing.JFrame {

    /**
     * Creates new form Kelola_Barang
     */
    public Kelola_barang() {
        initComponents();
    
}
public void tampilkanBarangKeTabelK() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Kategori");
    model.addColumn("Stok");
    model.addColumn("Harga Jual");
    model.addColumn("Nama Supplier");
    model.addColumn("Tanggal Kadaluarsa");

    try (Connection conn = Koneksi.getKoneksi();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(
            "SELECT bj.kode_barang, bj.nama_barang, bj.kategori_barang, " +
            "SUM(sg.jumlah_stok) AS total_stok, sg.harga_jual, sb.nama_supplier, " +
            "MIN(sg.tanggal_kadaluarsa) AS tanggal_kadaluarsa " +
            "FROM barang_jual bj " +
            "JOIN stok_gudang sg ON bj.id_barang_jual = sg.id_barang_jual " +
            "JOIN supplier_barang sb ON sg.id_supplier_barang = sb.id_supplier_barang " +
            "GROUP BY bj.kode_barang, bj.nama_barang, bj.kategori_barang, sg.harga_jual, sb.nama_supplier " +
            "ORDER BY tanggal_kadaluarsa ASC"
         )) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kode_barang"),
                rs.getString("nama_barang"),
                rs.getString("kategori_barang"),
                rs.getInt("total_stok"),
                rs.getString("harga_jual"),
                rs.getString("nama_supplier"),
                rs.getString("tanggal_kadaluarsa")
            });
        }

        TabelK.setModel(model);
        System.out.println("DEBUG: Data berhasil dimuat ke tabel");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
        e.printStackTrace(); // << WAJIB kalau gagal
    }


}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientPanel();
        TambahbarangK = new javax.swing.JButton();
        TambahstokK = new javax.swing.JButton();
        TbarangterlarisK = new javax.swing.JScrollPane();
        TabelK = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        DashboardK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TambahbarangK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        TambahbarangK.setText("Tambah Barang+");
        TambahbarangK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahbarangKActionPerformed(evt);
            }
        });

        TambahstokK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        TambahstokK.setText("Tambak Stok+");
        TambahstokK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahstokKActionPerformed(evt);
            }
        });

        TabelK.setFont(new java.awt.Font("Poppins", java.awt.Font.BOLD, 14)
        );
        TabelK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbarangterlarisK.setViewportView(TabelK);

        DashboardK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        DashboardK.setText("Dashboard");
        DashboardK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardK)
                .addGap(89, 89, 89))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(TambahbarangK)
                .addGap(116, 116, 116)
                .addComponent(TambahstokK)
                .addGap(142, 834, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbarangterlarisK)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahbarangK)
                    .addComponent(TambahstokK))
                .addGap(94, 94, 94)
                .addComponent(TbarangterlarisK, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahbarangKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahbarangKActionPerformed
        tambah_barang tb = new tambah_barang(new javax.swing.JFrame(), true);
        tb.setVisible(true);
        tb.pack();
        tb.setLocationRelativeTo(null);

    }//GEN-LAST:event_TambahbarangKActionPerformed

    private void DashboardKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardKActionPerformed
       String role = Session.getCurrentUserRole();
Dashboard da = new Dashboard(role);
da.setVisible(true);
da.pack();
da.setLocationRelativeTo(null);
dispose();

    }//GEN-LAST:event_DashboardKActionPerformed

    private void TambahstokKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahstokKActionPerformed
        tambah_stok tb = new tambah_stok(new javax.swing.JFrame(), true);
        tb.setVisible(true);
        tb.pack();
        tb.setLocationRelativeTo(null);
    }//GEN-LAST:event_TambahstokKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
            UIManager.put("Button.arc", 999);
            UIManager.put("defaultFont", new Font("Poppins", Font.BOLD, 14));

        } catch (Exception ex) {
            System.err.println("Gagal mengatur tema FlatLaf Arc Orange.");
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelola_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DashboardK;
    private javax.swing.JTable TabelK;
    private javax.swing.JButton TambahbarangK;
    private javax.swing.JButton TambahstokK;
    private javax.swing.JScrollPane TbarangterlarisK;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
