/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import kasir_warmad.Koneksi;

/**
 *
 * @author ThinkPad
 */
public class Retur extends javax.swing.JFrame {

    /**
     * Creates new form Retur
     */
    public Retur() {
        initComponents();
         IsiKategori();
        IsiBarang();
    }
private void IsiKategori() {
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT DISTINCT kategori_barang FROM barang_jual";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        PilihkategoriR.removeAllItems();
        while (rs.next()) {
            PilihkategoriR.addItem(rs.getString("kategori_barang"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat kategori: " + e.getMessage());
    }
}

// 2. Mengisi ComboBox Barang Berdasarkan Kategori
private void IsiBarang() {
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT nama_barang FROM barang_jual WHERE kategori_barang = ?";
        PreparedStatement ps = conn.prepareStatement(sql);

        String kategoriDipilih = PilihkategoriR.getSelectedItem().toString();
        ps.setString(1, kategoriDipilih);

        ResultSet rs = ps.executeQuery();

        PilihbarangR.removeAllItems();
        while (rs.next()) {
            PilihbarangR.addItem(rs.getString("nama_barang"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat barang: " + e.getMessage());
    }
}

// 3. Menampilkan Barang dari stok_gudang ke TabelR
private void TampilkanbarangR() {
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT bj.id_barang_jual, bj.nama_barang, bj.kategori_barang, sg.jumlah_stok, sg.tanggal_kadaluarsa "
                   + "FROM stok_gudang sg "
                   + "JOIN barang_jual bj ON sg.id_barang_jual = bj.id_barang_jual "
                   + "WHERE bj.kategori_barang = ? AND bj.nama_barang = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, PilihkategoriR.getSelectedItem().toString());
        ps.setString(2, PilihbarangR.getSelectedItem().toString());

        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Stok");
        model.addColumn("Tanggal Kadaluarsa");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_barang_jual"),
                rs.getString("nama_barang"),
                rs.getString("kategori_barang"),
                rs.getInt("jumlah_stok"),
                rs.getDate("tanggal_kadaluarsa")
            });
        }

        TabelR.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data stok: " + e.getMessage());
    }
}
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PilihkategoriR = new javax.swing.JComboBox<>();
        PilihbarangR = new javax.swing.JComboBox<>();
        TampilkanbarangR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelR = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReturbarangR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DashboardR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PilihkategoriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihkategoriRActionPerformed(evt);
            }
        });

        PilihbarangR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihbarangRActionPerformed(evt);
            }
        });

        TampilkanbarangR.setText("Tampilkan Barang");
        TampilkanbarangR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanbarangRActionPerformed(evt);
            }
        });

        TabelR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Stok", "Tanggal_Kadaluarsa"
            }
        ));
        jScrollPane1.setViewportView(TabelR);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Kategori");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pilih Barang");

        ReturbarangR.setText("RETUR");
        ReturbarangR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturbarangRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(PilihkategoriR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(PilihbarangR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TampilkanbarangR)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ReturbarangR)
                        .addGap(127, 127, 127))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jLabel1)
                            .addGap(258, 258, 258)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)))
                    .addGap(3, 3, 3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PilihkategoriR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PilihbarangR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TampilkanbarangR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(ReturbarangR)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        DashboardR.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        DashboardR.setText("Dashboard");
        DashboardR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardR)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardR)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihkategoriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihkategoriRActionPerformed
        IsiBarang();
    }//GEN-LAST:event_PilihkategoriRActionPerformed

    private void PilihbarangRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihbarangRActionPerformed

    }//GEN-LAST:event_PilihbarangRActionPerformed

    private void TampilkanbarangRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanbarangRActionPerformed
TampilkanbarangR();
      
    }//GEN-LAST:event_TampilkanbarangRActionPerformed

    private void ReturbarangRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturbarangRActionPerformed
  try {
    int selectedRow = TabelR.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih barang yang akan diretur!");
        return;
    }

    String idBarang = TabelR.getValueAt(selectedRow, 0).toString();
    String namaBarang = TabelR.getValueAt(selectedRow, 1).toString();
    int stok = Integer.parseInt(TabelR.getValueAt(selectedRow, 3).toString());

    String inputJumlah = JOptionPane.showInputDialog(null, "Masukkan jumlah retur:", "Retur Barang", JOptionPane.PLAIN_MESSAGE);
    if (inputJumlah == null) return;

    int jumlahRetur = Integer.parseInt(inputJumlah);

    if (jumlahRetur <= 0 || jumlahRetur > stok) {
        JOptionPane.showMessageDialog(null, "Jumlah retur tidak valid!");
        return;
    }

    Connection conn = Koneksi.getKoneksi();

    // Kurangi stok
    String sqlUpdate = "UPDATE stok_gudang SET jumlah_stok = jumlah_stok - ? WHERE id_barang_jual = ?";
    PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
    psUpdate.setInt(1, jumlahRetur);
    psUpdate.setString(2, idBarang);
    psUpdate.executeUpdate();

    // Generate id_retur
    String idRetur = generateIdRetur();

    // Simpan ke tabel retur_barang
    String sqlInsert = "INSERT INTO retur_barang (id_retur, id_barang_jual, nama_barang, jumlah_retur, tanggal_retur) "
                     + "VALUES (?, ?, ?, ?, CURRENT_DATE())";
    PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
    psInsert.setString(1, idRetur);
    psInsert.setString(2, idBarang);
    psInsert.setString(3, namaBarang);
    psInsert.setInt(4, jumlahRetur);
    psInsert.executeUpdate();

    JOptionPane.showMessageDialog(null, "Retur berhasil disimpan.");

    TampilkanbarangR(); // refresh stok

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal retur barang: " + e.getMessage());
}




    }//GEN-LAST:event_ReturbarangRActionPerformed

    private void DashboardRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardRActionPerformed
        String role = Session.getCurrentUserRole();
Dashboard da = new Dashboard(role);
da.setVisible(true);
da.pack();
da.setLocationRelativeTo(null);
dispose();

    }//GEN-LAST:event_DashboardRActionPerformed
private String generateIdRetur() {
    String prefix = "RTRBRNG";
    int nomor = 1;

    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT id_retur FROM retur_barang ORDER BY id_retur DESC LIMIT 1";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String lastId = rs.getString("id_retur"); // contoh: RTRBRNG25001
            if (lastId != null && lastId.length() >= 12) {
                String numPart = lastId.substring(7); // ambil "25001"
                nomor = Integer.parseInt(numPart) + 1;
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal generate ID Retur: " + e.getMessage());
    }

    return prefix + String.format("%05d", nomor); // Hasil: RTRBRNG25002
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
            UIManager.put("Button.arc", 999);
            UIManager.put("defaultFont", new Font("Poppins", Font.BOLD, 14));
            Object put = UIManager.put("Component.arrowType", "triangle");
        } catch (Exception ex) {
            System.err.println("Gagal mengatur tema FlatLaf Arc Orange.");
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DashboardR;
    private javax.swing.JComboBox<String> PilihbarangR;
    private javax.swing.JComboBox<String> PilihkategoriR;
    private javax.swing.JButton ReturbarangR;
    private javax.swing.JTable TabelR;
    private javax.swing.JButton TampilkanbarangR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
